#!/usr/bin/perl
#
##
##########################################################################
#                                                                        #
#       Google Authenticator Automator                                   #
#       Unix Registration System                                         #
#                                                                        #
#       Copyright (C) 2012 by Vamegh Hedayati                            #
#       vamegh <AT> gmail.com                                            #
#                                                                        #
#       Please see Copying for License Information                       #
#                               GNU/GPL v2 2010                          #
##########################################################################
##
#
#################################################
##
# Integrity Checks
##
use strict;
use warnings;
#################################################
# My Modules
##
# provided in the following locations:
##
use lib qw(/opt/gauth);
use lib qw(./libs);
##
# These should be available by default
##
use libs::UserDetails;
use libs::LogHandle;
use libs::CMDHandle;
use libs::AuthHandler;
use libs::LDAPCON;
use libs::DBCON;
use libs::MailHandler;
use libs::QRHandler;
use libs::FileHandler;

#################################################
# Local Internal Variables for this script
##
my $myname="PAM-LDAPCHECK :: Google Authenticator Automator :: LDAP OU Unix Checker / Registration System";
my $caller="$myname";
#################################################
#  Sub-Routines / Functions Definitions
##
my $cfg_file="/opt/gauth/cfgs/pam-ldapcheck.cfg";
&cmd_handle;
&read_cfg("cfgpars","$cfg_file");
&user_info;

if ($sys_pam) {
  &log_loc($log_dir,$sys_pam."_ldap-check.log");
  &user_info;
  &log_it("Starting Program Run",
          "debug","1",$caller);
  &log_it("Pam user currently set to $sys_pam ",
          "debug","3",$caller);
} else {
  &log_loc($log_dir,$auth_name."_ldap-check.log");
  &user_info;
  &log_it("Starting Program Run",
          "debug","1",$caller);
  &log_it("Pam user currently set to $sys_pam ",
          "debug","3",$caller);
}


&ldap_check("verify");
&ldap_check("unix");

##
#################################################
#
################################### EO PROGRAM #######################################################
#
################################ MODULE HELP / DOCUMENTATION SECTION #################################
##
# Original implementation idea from linblock.pl http://www.dessent.net/linblock/ (c) Brian Dessent GNU/GPL
# This actually uses no code from linblock.pl, but the implementation was learnt by studying the above script
##
# To access documentation please use perldoc CMDHandle.pm, This will provide
# the formatted help file for this specific module
##
#################################################
#
__END__

=head1 NAME

PAM-LDAPCHECK - Google Authenticator Automator

=head1 SYNOPSIS

PAM-LDAPCHECK  - Google Authenticator Automator
  This should only be run via PAM, this should not be invoked manually

       --help for more information or perldoc pam-ldapcheck

=head1 DESCRIPTION

This program / script scans the user on first connection into the system to ensure the user is set up in LDAP.

It can also be used to enable the user in LDAP OU=unix, but currently this feature is disabled by request of peers,
due to possible security concerns / internal politics.

This script _MUST_ be invoked by PAM and should never be called manually. it uses the same libraries as gauth and is closely linked
into the gauth system.

=head1 OPTIONS

The command line options for pam-ldapcheck are as follows:

=over

=item I<add colour>

Uses Term::Ansicolor to colourise the logging. If not specified, no colour is output.

=item -D I<dont log to file>

Doesnt log to file, instead outputs everything to the command line.
With this specified -L will be ignored

=item -v I<Specify Verbosity Level>

Verbosity Level

I<1> verbosity low C<(-v 1)>

I<2> Verbosity medium C<(-v 2)>

I<3> Verbosity High C<(-v 3)>

=item -U I<Specify the Username to Check>

This option is very useful / bordering necessary.
This sets the username that should be checked,
if this option is not set the person running the script will be used for username.
When this program is invoked by the PAM scripts,
this option is set to the PAM_USER environment variable i.e -U is called.

=item -l I<Use LDAP>

Specify whether or not to use ldap to do user verification.
This must be either yes or no. By default the configuration values from the config file are read in.
Please do not set this via the command line, please use the configuration file.
Please also note the search field is currently ignored.
If you specify this you need to specify the following:

LDAP Base C<(-b)>

LDAP Bind C<(-n)>

LDAP Server C<(-s)>

LDAP Search C<(-S)>

LDAP Pass C<(-w)>

Along with the mentioned flags,  this will not work without all of the above information

=item -b I<LDAP Base>

Specify the Base LDAP Tree to examine.
This must be used in conjuction with -l, the use ldap option detailed above.

=item -n I<LDAP Bind>

Specify the Bind address, This is the username bind.
Please set this to anon, if you wish to bind anonymously.
This must be used in conjuction with -l, the use ldap option detailed above.

=item -s I<LDAP Server>

Specify the Server address to use.
This must be used in conjuction with -l, the use ldap option detailed above.

=item -S I<LDAP Search>

Specify the LDAP Search string, (this is currently ignored)
This must be used in conjuction with -l, the use ldap option detailed above.

=item -w I<LDAP Pass>

Specify the Bind Password, This is the password for the username specified in bind address.
Please set this to anon, if you wish to bind anonymously.
This must be used in conjuction with -l, the use ldap option detailed above.

=item -E I<Use Email>

Specify whether or not to use Email Subsystem.
This must be either yes or no. By default the configuration values from the config file are read in.
Please do not set this via the command line, please use the configuration file.
If you specify this you can also specify the following:

=item -m I<Mail To>

Specify the email address to send emails to.

=item -M I<Mail From>

Specify the email address to send emails from.

=item -H I<Mail Host>

Specify the mail server Host.

=item --help

Print command line options summary.  For more detailed help, type C<perldoc -F pam-ldapcheck>.

=item --version

Prints the version information.

=back

=head1 AUTHOR

=over

=item Vamegh Hedayati <vamegh AT gmail DOT com>

=back

=head1 LICENSE

Copyright (C) 2010 / 2012  Vamegh Hedayati <vamegh AT gmail DOT com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

Please refer to the COPYING file which is distributed with Gauth
for the full terms and conditions

=cut
#
#################################################
#
######################################### EOF  #######################################################

